"""Updated note model for collaborators

Revision ID: f03f2c4849ac
Revises: e5ce9770dc6f
Create Date: 2024-10-15 10:28:45.325413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f03f2c4849ac'
down_revision: Union[str, None] = 'e5ce9770dc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('collaborators', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")))    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'collaborators')
    # ### end Alembic commands ###
